// <auto-generated />
using System;
using InternshipManager.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InternshipManager.Api.Migrations.Shared
{
    [DbContext(typeof(SharedDbContext))]
    [Migration("20260404022852_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InternshipManager.Api.Models.Shared.Address", b =>
                {
                    b.Property<int>("IdAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAddress"));

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("IdDepartment")
                        .HasColumnType("integer");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdAddress");

                    b.HasIndex("IdDepartment");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Shared.Department", b =>
                {
                    b.Property<int>("IdDepartment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDepartment"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdDepartment");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Shared.Employee", b =>
                {
                    b.Property<Guid>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("IdDepartment")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PersonnelNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("IdEmployee");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdDepartment");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("PersonnelNumber")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Shared.PracticeType", b =>
                {
                    b.Property<int>("IdPracticeType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPracticeType"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdPracticeType");

                    b.ToTable("PracticeTypes");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Shared.ScheduledPractice", b =>
                {
                    b.Property<int>("IdScheduledPractice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdScheduledPractice"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPracticeType")
                        .HasColumnType("integer");

                    b.Property<int>("IdSpecialization")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdScheduledPractice");

                    b.HasIndex("IdPracticeType");

                    b.HasIndex("IdSpecialization");

                    b.ToTable("ScheduledPractices");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Shared.Specialization", b =>
                {
                    b.Property<int>("IdSpecialization")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSpecialization"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdSpecialization");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Shared.Address", b =>
                {
                    b.HasOne("InternshipManager.Api.Models.Shared.Department", "Department")
                        .WithMany("Addresses")
                        .HasForeignKey("IdDepartment")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Shared.Employee", b =>
                {
                    b.HasOne("InternshipManager.Api.Models.Shared.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("IdDepartment")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Shared.ScheduledPractice", b =>
                {
                    b.HasOne("InternshipManager.Api.Models.Shared.PracticeType", "PracticeType")
                        .WithMany("ScheduledPractices")
                        .HasForeignKey("IdPracticeType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternshipManager.Api.Models.Shared.Specialization", "Specialization")
                        .WithMany("ScheduledPractices")
                        .HasForeignKey("IdSpecialization")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PracticeType");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Shared.Department", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Shared.PracticeType", b =>
                {
                    b.Navigation("ScheduledPractices");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Shared.Specialization", b =>
                {
                    b.Navigation("ScheduledPractices");
                });
#pragma warning restore 612, 618
        }
    }
}
