// <auto-generated />
using System;
using InternshipManager.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InternshipManager.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260406104616_AddInterviewAndSlotUpdates")]
    partial class AddInterviewAndSlotUpdates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InternshipManager.Api.Models.Shared.Address", b =>
                {
                    b.Property<int>("IdAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAddress"));

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("IdDepartment")
                        .HasColumnType("integer");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdAddress");

                    b.HasIndex("IdDepartment");

                    b.ToTable("Addresses", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Shared.Department", b =>
                {
                    b.Property<int>("IdDepartment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDepartment"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdDepartment");

                    b.ToTable("Departments", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Shared.Employee", b =>
                {
                    b.Property<Guid>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("IdDepartment")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PersonnelNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("IdEmployee");

                    b.HasIndex("IdDepartment");

                    b.ToTable("Employees", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Shared.PracticeType", b =>
                {
                    b.Property<int>("IdPracticeType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPracticeType"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdPracticeType");

                    b.ToTable("PracticeTypes", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Shared.ScheduledPractice", b =>
                {
                    b.Property<int>("IdScheduledPractice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdScheduledPractice"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPracticeType")
                        .HasColumnType("integer");

                    b.Property<int>("IdSpecialization")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdScheduledPractice");

                    b.HasIndex("IdPracticeType");

                    b.HasIndex("IdSpecialization");

                    b.ToTable("ScheduledPractices", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Shared.Specialization", b =>
                {
                    b.Property<int>("IdSpecialization")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSpecialization"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdSpecialization");

                    b.ToTable("Specializations", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.Interview", b =>
                {
                    b.Property<int>("IdInterviewSlot")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdStudentApplication")
                        .HasColumnType("uuid");

                    b.Property<int>("InterviewType")
                        .HasColumnType("integer");

                    b.Property<bool>("Result")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdInterviewSlot");

                    b.ToTable("Interviews");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.InterviewSlot", b =>
                {
                    b.Property<int>("IdInterviewSlot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInterviewSlot"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IdCreator")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEmployee")
                        .HasColumnType("uuid");

                    b.Property<int>("IdInterval")
                        .HasColumnType("integer");

                    b.Property<Guid?>("IdSupervisorApplication")
                        .HasColumnType("uuid");

                    b.Property<string>("MeetingPlace")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RejectionComment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdInterviewSlot");

                    b.HasIndex("IdInterval");

                    b.ToTable("InterviewSlots");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.StudentSupervisorApplication", b =>
                {
                    b.Property<Guid>("IdSupervisorApplication")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdStudentApplication")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdSupervisorApplication", "IdStudentApplication");

                    b.ToTable("StudentSupervisorApplications");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.SupervisorApplication", b =>
                {
                    b.Property<Guid>("IdSupervisorApplication")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdAddress")
                        .HasColumnType("integer");

                    b.Property<Guid?>("IdCreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("IdDepartment")
                        .HasColumnType("integer");

                    b.Property<Guid>("IdEmployee")
                        .HasColumnType("uuid");

                    b.Property<int?>("IdScheduledPractice")
                        .HasColumnType("integer");

                    b.Property<int>("IdSpecialization")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<int>("PracticeFormat")
                        .HasColumnType("integer");

                    b.Property<int>("RequestedStudentsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdSupervisorApplication");

                    b.ToTable("SupervisorApplications");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.SupervisorReview", b =>
                {
                    b.Property<Guid>("IdEmployee")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdStudentApplication")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IndependenceScore")
                        .HasColumnType("integer");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<int>("PvScore")
                        .HasColumnType("integer");

                    b.Property<bool>("RecommendedForEmployment")
                        .HasColumnType("boolean");

                    b.Property<int>("SkillsScore")
                        .HasColumnType("integer");

                    b.Property<int>("TeamworkScore")
                        .HasColumnType("integer");

                    b.HasKey("IdEmployee", "IdStudentApplication");

                    b.ToTable("SupervisorReviews");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.TimeInterval", b =>
                {
                    b.Property<int>("IdInterval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInterval"));

                    b.Property<TimeSpan?>("BreakDuration")
                        .HasColumnType("interval");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IdCreator")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEmployee")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdInterval");

                    b.ToTable("TimeIntervals");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Shared.Address", b =>
                {
                    b.HasOne("InternshipManager.Api.Models.Shared.Department", "Department")
                        .WithMany("Addresses")
                        .HasForeignKey("IdDepartment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Shared.Employee", b =>
                {
                    b.HasOne("InternshipManager.Api.Models.Shared.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("IdDepartment");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Shared.ScheduledPractice", b =>
                {
                    b.HasOne("InternshipManager.Api.Models.Shared.PracticeType", "PracticeType")
                        .WithMany("ScheduledPractices")
                        .HasForeignKey("IdPracticeType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternshipManager.Api.Models.Shared.Specialization", "Specialization")
                        .WithMany("ScheduledPractices")
                        .HasForeignKey("IdSpecialization")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticeType");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.Interview", b =>
                {
                    b.HasOne("InternshipManager.Api.Models.Supervisor.InterviewSlot", "InterviewSlot")
                        .WithOne("Interview")
                        .HasForeignKey("InternshipManager.Api.Models.Supervisor.Interview", "IdInterviewSlot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterviewSlot");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.InterviewSlot", b =>
                {
                    b.HasOne("InternshipManager.Api.Models.Supervisor.TimeInterval", "TimeInterval")
                        .WithMany("InterviewSlots")
                        .HasForeignKey("IdInterval")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeInterval");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.StudentSupervisorApplication", b =>
                {
                    b.HasOne("InternshipManager.Api.Models.Supervisor.SupervisorApplication", "SupervisorApplication")
                        .WithMany("StudentSupervisorApplications")
                        .HasForeignKey("IdSupervisorApplication")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupervisorApplication");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Shared.Department", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Shared.PracticeType", b =>
                {
                    b.Navigation("ScheduledPractices");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Shared.Specialization", b =>
                {
                    b.Navigation("ScheduledPractices");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.InterviewSlot", b =>
                {
                    b.Navigation("Interview");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.SupervisorApplication", b =>
                {
                    b.Navigation("StudentSupervisorApplications");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.TimeInterval", b =>
                {
                    b.Navigation("InterviewSlots");
                });
#pragma warning restore 612, 618
        }
    }
}
