// <auto-generated />
using System;
using InternshipManager.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InternshipManager.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.Interview", b =>
                {
                    b.Property<int>("IdInterviewSlot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdStudentApplication")
                        .HasColumnType("integer");

                    b.Property<int>("InterviewType")
                        .HasColumnType("integer");

                    b.Property<bool>("Result")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdInterviewSlot");

                    b.ToTable("Interviews");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.InterviewSlot", b =>
                {
                    b.Property<int>("IdInterviewSlot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInterviewSlot"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdCreator")
                        .HasColumnType("integer");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("integer");

                    b.Property<int>("IdInterval")
                        .HasColumnType("integer");

                    b.Property<int?>("IdSupervisorApplication")
                        .HasColumnType("integer");

                    b.Property<string>("MeetingPlace")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RejectionComment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdInterviewSlot");

                    b.HasIndex("IdInterval");

                    b.ToTable("InterviewSlots");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.StudentSupervisorApplication", b =>
                {
                    b.Property<int>("IdSupervisorApplication")
                        .HasColumnType("integer");

                    b.Property<int>("IdStudentApplication")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdSupervisorApplication", "IdStudentApplication");

                    b.ToTable("StudentSupervisorApplications");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.SupervisorApplication", b =>
                {
                    b.Property<int>("IdSupervisorApplication")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSupervisorApplication"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdAddress")
                        .HasColumnType("integer");

                    b.Property<int?>("IdCreatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("IdDepartment")
                        .HasColumnType("integer");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("integer");

                    b.Property<int?>("IdScheduledPractice")
                        .HasColumnType("integer");

                    b.Property<int>("IdSpecialization")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<int>("PracticeFormat")
                        .HasColumnType("integer");

                    b.Property<int>("RequestedStudentsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdSupervisorApplication");

                    b.ToTable("SupervisorApplications");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.SupervisorReview", b =>
                {
                    b.Property<int>("IdEmployee")
                        .HasColumnType("integer");

                    b.Property<int>("IdStudentApplication")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IndependenceScore")
                        .HasColumnType("integer");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<int>("PvScore")
                        .HasColumnType("integer");

                    b.Property<bool>("RecommendedForEmployment")
                        .HasColumnType("boolean");

                    b.Property<int>("SkillsScore")
                        .HasColumnType("integer");

                    b.Property<int>("TeamworkScore")
                        .HasColumnType("integer");

                    b.HasKey("IdEmployee", "IdStudentApplication");

                    b.ToTable("SupervisorReviews");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.TimeInterval", b =>
                {
                    b.Property<int>("IdInterval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInterval"));

                    b.Property<TimeSpan?>("BreakDuration")
                        .HasColumnType("interval");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdCreator")
                        .HasColumnType("integer");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("integer");

                    b.Property<int>("MaxCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdInterval");

                    b.ToTable("TimeIntervals");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.Interview", b =>
                {
                    b.HasOne("InternshipManager.Api.Models.Supervisor.InterviewSlot", "InterviewSlot")
                        .WithOne("Interview")
                        .HasForeignKey("InternshipManager.Api.Models.Supervisor.Interview", "IdInterviewSlot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterviewSlot");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.InterviewSlot", b =>
                {
                    b.HasOne("InternshipManager.Api.Models.Supervisor.TimeInterval", "TimeInterval")
                        .WithMany("InterviewSlots")
                        .HasForeignKey("IdInterval")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeInterval");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.StudentSupervisorApplication", b =>
                {
                    b.HasOne("InternshipManager.Api.Models.Supervisor.SupervisorApplication", "SupervisorApplication")
                        .WithMany("StudentSupervisorApplications")
                        .HasForeignKey("IdSupervisorApplication")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupervisorApplication");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.InterviewSlot", b =>
                {
                    b.Navigation("Interview");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.SupervisorApplication", b =>
                {
                    b.Navigation("StudentSupervisorApplications");
                });

            modelBuilder.Entity("InternshipManager.Api.Models.Supervisor.TimeInterval", b =>
                {
                    b.Navigation("InterviewSlots");
                });
#pragma warning restore 612, 618
        }
    }
}
